version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/linode/linodego
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            go get -u gopkg.in/alecthomas/gometalinter.v2
            gometalinter.v2 --install
            touch .env
      - run:
          name: "Run Tests"
          command: |
            make test ARGS='-v -race -count=2 -coverprofile=coverage.txt -covermode=atomic ./...'
      - run:
          name: "Run Linter"
          command: |
            gometalinter.v2 --enable-all --disable=vetshadow --disable=gocyclo --disable=unparam --disable=nakedret --disable=lll --disable=dupl --disable=gosec --disable=gochecknoinits --disable=gochecknoglobals --disable=test --deadline=120s
            gometalinter.v2 --disable-all --enable=vetshadow --enable=gocyclo --enable=unparam --enable=nakedret --enable=lll --enable=dupl --enable=gosec --enable=gochecknoinits --enable=gochecknoglobals --deadline=120s || true
      - run:
          name: "Upload Coverage"
          command: bash <(curl -s https://codecov.io/bash)
